name: CI Pipeline
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Sabit sürüm belirt
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          
      - name: List files (Debug)
        run: ls -R  # Dosya yapısını kontrol
          
      - name: Run tests
        run: |
          pytest tests/ -v
          # VEYA spesifik dosya için:
          # pytest tests/test_example.py -v
